gotspoilergenwebservice/config/routes.rb
Rails.application.routes.draw do
  post 'api_rest/index'
  get 'admin_areas/index'
  get 'welcome/index'
  root 'welcome#index'
  
  devise_for :users, :path_prefix => 'd' # routes for devise modules on User
  resources :users # custom admin-type CRUD for users
  resources :things
  resources :places
  resources :people

 

end

gotspoilergenwebservice/app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, presence: true
  def self.search(query)
  	where("name LIKE ?", "%#{query}%")
  end
end

gotspoilergenwebservice/app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /places
  # GET /places.json
  def index
    if(params.has_key?(:search))
      @places = Place.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
    else
      @places = Place.paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name)
    end
end

gotspoilergenwebservice/app/helpers/places_helper.rb
module PlacesHelper
end

gotspoilergenwebservice/app/views/places/_form.html.erb
<%= form_for @place, :html => { :class => "form-horizontal place" } do |f| %>

  <% if @place.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                places_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

gotspoilergenwebservice/app/views/places/edit.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

gotspoilergenwebservice/app/views/places/index.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_tag(places_path, method: :get) do %>
  <div class="col-lg-10">
    <%= text_field_tag 'search', nil, placeholder: 'Digite sua pesquisa',  :class => 'form-control'%>
  </div>
  <div class="col-lg-2">
    <%= submit_tag "Pesquisar", :class => 'btn btn-default'%>
  </div><br>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.id, place_path(place) %></td>
        <td><%= place.name %></td>
        <td><%=l place.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_place_path(place), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @place, renderer: BootstrapPagination::Rails %>
<br>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_place_path,
            :class => 'btn btn-primary' %>

gotspoilergenwebservice/app/views/places/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

gotspoilergenwebservice/app/views/places/show.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @place.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              places_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_place_path(@place), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>