gotspoilergen/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/index'
  get 'gen/index'
  root 'welcome#index'
  

 

end

gotspoilergen/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

gotspoilergen/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require "uri"
  require "net/http"

  def index
    uriAPI = 'http://gotspoilergenwebservice.herokuapp.com/api_rest/index.json'
  	if(enc_uri_is_set)
	  	peopleId, placesId, thingsId = self.params_decode
	  	if(!peopleId.nil? && !placesId.nil? && !thingsId.nil?)
  		  paramsAPI = {'auth_request_key' => '62b15f01097ad285ca8162829afa86ae',
  					   'command' => 'get_selected_values',
  					   'idPeople' => peopleId,
  					   'idThings' => thingsId,
  					   'idPlaces' => placesId}
  		  resposta_http = Net::HTTP.post_form(URI.parse(uriAPI), paramsAPI)
  		  @parsed_json = JSON.parse(resposta_http.body)
	  	end
  	else
		  paramsAPI = {'auth_request_key' => '62b15f01097ad285ca8162829afa86ae',
					   'command' => 'get_one_random_string'}

		  resposta_http = Net::HTTP.post_form(URI.parse(uriAPI), paramsAPI)
		  @parsed_json = JSON.parse(resposta_http.body)
  	end	
  end

  def params_decode
  	if(params.has_key?(:enc_uri))
  		strUri = params[:enc_uri]
  		strUri = strUri.sub("xZ3", "!") 
  		strUri = strUri.sub("p3x", "!")
  		strUri = strUri.sub("m12", "!")

  		index_of = strUri.index("!",1)
  		peopleNumber = strUri[1..index_of-1] 
  		index_ini = index_of+1	
  		index_of = strUri.index("!",index_ini	)
  		placesNumber = strUri[index_ini..index_of-1]
  		index_ini = index_of+1
  		thingsNumber = strUri[index_ini..strUri.length]

  		return peopleNumber.to_i, placesNumber.to_i, thingsNumber.to_i
   	else
  		return nil
  	end
  end

  def enc_uri_is_set
  	if(params.has_key?(:enc_uri))
  	  return true
  	else
  	  return false
  	end
  end
end

gotspoilergen/app/helpers/application_helper.rb
module ApplicationHelper
end

gotspoilergen/app/helpers/welcome_helper.rb
module WelcomeHelper
end

gotspoilergen/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "#{@parsed_json["values"]["string"]}" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72.png', :rel => 'apple-touch-icon', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <ul class="nav navbar-nav">
          <%= link_to "GoT: Spoiler Generator", root_path, :class => 'navbar-brand' %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
        <div class="navbar-text">
          &copy; Marcelo Martins e John Reis
        </div>
      </footer>

    </div>
  </body>
</html>

gotspoilergen/app/views/welcome/index.html.erb
<% spoiler_strng = "#{@parsed_json["values"]["string"]}"%>
<% enc_uri = "#{@parsed_json["values"]["enc_uri"]}"%>


<div class="text-center">
	<h1><%= spoiler_strng %></h1>
	<br>
	<%= image_tag @parsed_json["values"]["image"], :class => 'img-rounded img-responsive center-block'%>
	<br><br>
	<%= link_to "Generate", welcome_index_path, :method => :get, :class => 'btn btn-default btn-lg'%>
	<br><br>
	<%= social_share_button_tag(spoiler_strng, 
	:popup => "true", 
	:url => enc_uri,
	desc: spoiler_strng,
	'data-twitter-title' => spoiler_strng,
	'data-facebook-title' => spoiler_strng)%>
	<br><br>
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
			</div>
			<div class="col-lg-2 gauche">
				<button class="btn btn-danger" data-clipboard-action="cut" data-clipboard-target="#ShareLink">
			    	Copy To Clipboard!
				</button>
			</div>
			<div class="col-lg-4 corps">
				<%= text_field "ShareLink", "ShareLink", :class => 'form-control js-copytextarea', :value =>  enc_uri, :id=>"ShareLink", :readonly => true%>
			</div>
	  		<div class="col-lg-3">
	  		</div>
	 	</div>
	</div>
	<br><br><br><br>
</div>