gotspoilergenwebservice/config/routes.rb
Rails.application.routes.draw do
  post 'api_rest/index'
  get 'admin_areas/index'
  get 'welcome/index'
  root 'welcome#index'
  
  devise_for :users, :path_prefix => 'd' # routes for devise modules on User
  resources :users # custom admin-type CRUD for users
  resources :things
  resources :places
  resources :people

 

end

gotspoilergenwebservice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GotSpoilerGenWebservice" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "GSGen Webservice", root_path, :class => 'navbar-brand' %>
        </div>
        <% if user_signed_in? == TRUE %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Personagens", people_path %></li>
            <li><%= link_to "Lugares", places_path %></li>
            <li><%= link_to "Acontecimentos", things_path %></li>
            <li><%= link_to "Área de Administração", admin_areas_index_path %></li>
          </ul>
          <ui class="pull-right">
            <%= link_to "#{current_user.email}", edit_user_registration_path, method: :get, :class => 'btn btn-default navbar-btn' %>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'btn btn-danger navbar-btn' %>
          </ui>
        <% else %>
          <ui class="pull-right">
            <%= link_to "Entrar",
              new_user_session_path, method: :get, :class => 'btn btn-danger navbar-btn' %>
          </ui>
          <li><%= link_to "#{current_user}", edit_user_registration_path, method: :get%></li>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <br><br><br><br><br>

      <footer class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
        <div class="navbar-text">
          &copy; Marcelo Martins e John Reis
        </div>
      </footer>

    </div> <!-- /container -->
  </body>
</html>