gotspoilergenwebservice/config/routes.rb
Rails.application.routes.draw do
  post 'api_rest/index'
  get 'admin_areas/index'
  get 'welcome/index'
  root 'welcome#index'
  
  devise_for :users, :path_prefix => 'd' # routes for devise modules on User
  resources :users # custom admin-type CRUD for users
  resources :things
  resources :places
  resources :people

 

end

gotspoilergenwebservice/app/models/thing.rb
class Thing < ActiveRecord::Base
  validates :name, presence: true
  def self.search(query)
  	where("name LIKE ?", "%#{query}%")
  end
end

gotspoilergenwebservice/app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /things
  # GET /things.json
  def index
    if(params.has_key?(:search))
      @things = Thing.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
    else
      @things = Thing.paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name)
    end
end

gotspoilergenwebservice/app/helpers/things_helper.rb
module ThingsHelper
end

gotspoilergenwebservice/app/views/things/_form.html.erb
<%= form_for @thing, :html => { :class => "form-horizontal thing" } do |f| %>

  <% if @thing.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @thing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                things_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

gotspoilergenwebservice/app/views/things/edit.html.erb
<%- model_class = Thing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

gotspoilergenwebservice/app/views/things/index.html.erb
<%- model_class = Thing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_tag(things_path, method: :get) do %>
  <div class="col-lg-10">
    <%= text_field_tag 'search', nil, placeholder: 'Digite sua pesquisa',  :class => 'form-control'%>
  </div>
  <div class="col-lg-2">
    <%= submit_tag "Pesquisar", :class => 'btn btn-default'%>
  </div><br>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= link_to thing.id, thing_path(thing) %></td>
        <td><%= thing.name %></td>
        <td><%=l thing.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_thing_path(thing), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      thing_path(thing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @things, renderer: BootstrapPagination::Rails %>
<br>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_thing_path,
            :class => 'btn btn-primary' %>

gotspoilergenwebservice/app/views/things/new.html.erb
<%- model_class = Thing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

gotspoilergenwebservice/app/views/things/show.html.erb
<%- model_class = Thing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @thing.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              things_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_thing_path(@thing), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              thing_path(@thing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>